//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartLearn.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartLearn.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 35380671	张尔翼	高三年级5班
        ///35380648	刘雅虹	高三年级5班
        ///35380665	胥霁航	高三年级5班
        ///35380642	贾志杰	高三年级5班
        ///35380667	晏梦锟	高三年级5班
        ///35380677	赵中元	高三年级5班
        ///35380636	陈泓瑞	高三年级5班
        ///35380670	袁泓毅	高三年级5班
        ///35380656	任正智	高三年级5班
        ///35380659	魏思璇	高三年级5班
        ///35380652	牛腾锐	高三年级5班
        ///35380640	何一航	高三年级5班
        ///35380672	张佳港	高三年级5班
        ///35380650	罗允铭	高三年级5班
        ///35380663	鲜润奇	高三年级5班
        ///35380638	杜雨芃	高三年级5班
        ///35380668	应宇恒	高三年级5班
        ///35380658	王庆	高三年级5班
        ///35380641	黄谦	高三年级5班
        ///35380661	吴王茂	高三年级5班
        ///35380674	张诗雨	高三年级5班
        ///35380673	张倩	高三年级5班
        ///35380649	刘宇航	高三年级5班
        ///35380666	徐冬羽	高三年级5班
        ///35380654	青纪 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string refer {
            get {
                return ResourceManager.GetString("refer", resourceCulture);
            }
        }
    }
}
